# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python backend

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres:10.8
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: root
#          POSTGRES_DB: github_actions
#        ports:
#          - 5432:5432
#        # needed because the postgres container does not provide a healthcheck
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
#    - names
#    - name: Run backend lint
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Run migrations
#      run: |
#        cd backend
#        python manage.py migrate
#
#    - name: Run tests
#      run: |
#        cd backend
#        python manage.py test

    - name: Install frontend dependency
      run: |
        cd frontend
        npm install
        sudo npm install eslint -g

    - name: Run frontend lint
      run: |
        cd frontend
        eslint . --max-warnings 0
